Zodi static
hke/Commander pull request #176
Opened 2024-03-27 01:31 UTC by hke

2024-03-27 09:22 UTC, hermda02 requested changes
Overall looks good - too many changes for a single merge as a large portion of the component infrastructure, sampling, as well as several experiments are all being added in the same merge.

Requests:
add `*~` to `.gitignore`
remove all files ending in `~` before merge
remove commented out lines before merge to avoid clutter

2024-03-27 09:22 UTC, hermda02 commented on commander3/parameter_files/defaults/bands/DIRBE/DIRBE_01_CIO_512.defaults~
emacs temporary file added to git repo - remove

2024-03-27 09:22 UTC, hermda02 commented on commander3/parameter_files/defaults/bands/DIRBE/DIRBE_02_CIO_256.defaults~
emacs temporary file added to git repo - remove

2024-03-27 09:22 UTC, hermda02 commented on commander3/parameter_files/defaults/bands/DIRBE/DIRBE_03_CIO_512.defaults~
emacs temporary file added to git repo - remove

2024-03-27 09:22 UTC, hermda02 commented on commander3/parameter_files/defaults/bands/DIRBE/DIRBE_04_CIO_512.defaults~
emacs temporary file added to git repo - remove

2024-03-27 09:22 UTC, hermda02 commented on commander3/parameter_files/defaults/bands/DIRBE/DIRBE_05_CIO_512.defaults~
emacs temporary file added to git repo - remove

2024-03-27 09:22 UTC, hermda02 commented on commander3/parameter_files/defaults/bands/DIRBE/DIRBE_06_CIO_512.defaults~
emacs temporary file added to git repo - remove

2024-03-27 09:22 UTC, hermda02 commented on commander3/parameter_files/defaults/bands/DIRBE/DIRBE_07_CIO_512.defaults~
emacs temporary file added to git repo - remove

2024-03-27 09:22 UTC, hermda02 commented on commander3/parameter_files/defaults/bands/DIRBE/DIRBE_08_CIO_512.defaults~
emacs temporary file added to git repo - remove

2024-03-27 09:22 UTC, hermda02 commented on commander3/parameter_files/defaults/bands/DIRBE/DIRBE_09_CIO_512.defaults~
emacs temporary file added to git repo - remove

2024-03-27 09:22 UTC, hermda02 commented on commander3/parameter_files/defaults/bands/DIRBE/DIRBE_10_CIO_512.defaults~
emacs temporary file added to git repo - remove

2024-03-27 09:22 UTC, hermda02 commented on commander3/parameter_files/defaults/bands/HFI/HFI_100_DIRBE.defaults~
emacs temporary file added to git repo - remove

2024-03-27 09:22 UTC, hermda02 commented on commander3/parameter_files/defaults/bands/HFI/HFI_143_DIRBE.defaults~
emacs temporary file added to git repo - remove

2024-03-27 09:22 UTC, hermda02 commented on commander3/parameter_files/defaults/bands/HFI/HFI_217_DIRBE.defaults~
emacs temporary file added to git repo - remove

2024-03-27 09:22 UTC, hermda02 commented on commander3/parameter_files/defaults/bands/HFI/HFI_353_DIRBE.defaults~
emacs temporary file added to git repo - removeemacs temporary file added to git repo - remove

2024-03-27 09:22 UTC, hermda02 commented on commander3/parameter_files/defaults/bands/HFI/HFI_545_DIRBE.defaults~
emacs temporary file added to git repo - remove

2024-03-27 09:22 UTC, hermda02 commented on commander3/parameter_files/defaults/bands/HFI/HFI_857_DIRBE.defaults~
emacs temporary file added to git repo - remove

2024-03-27 09:22 UTC, hermda02 commented on .gitignore
Should add a line to ignore *~ files so emacs temp files aren't accidentally added to the repo.

2024-03-27 09:22 UTC, hermda02 commented on commander3/parameter_files/defaults/components/dust/dust_DIRBE_localsampler.defaults
No COMP_T_INT_PRIOR values in default file - intentional?

2024-03-27 09:22 UTC, hermda02 commented on commander3/parameter_files/defaults/components/dust/dust_HFI_localsampler.defaults
No COMP_T_INT_PRIOR values in default file - intentional?

2024-03-27 09:22 UTC, hermda02 commented on commander3/parameter_files/defaults/components/dust/dust_LiteBIRD.defaults
Local sampler details not separated - not a problem, just inconsistent with older default file scheme

2024-03-27 09:22 UTC, hermda02 commented on commander3/parameter_files/defaults/components/freefree/freefreeEM_DIRBE.defaults~
emacs temporary file added to git repo - remove

2024-03-27 09:22 UTC, hermda02 commented on commander3/parameter_files/defaults/components/freefree/freefree_DIRBE.defaults~
emacs temporary file added to git repo - remove

2024-03-27 09:22 UTC, hermda02 commented on commander3/parameter_files/defaults/components/freefree/freefree_DIRBE2.defaults~
emacs temporary file added to git repo - remove

2024-03-27 09:22 UTC, hermda02 commented on commander3/parameter_files/defaults/components/synch/synch_LiteBIRD.defaults
Local sampler details not separated - not a problem, just inconsistent with older default file scheme

2024-03-27 09:22 UTC, hermda02 commented on commander3/parameter_files/defaults/components/zodi/old/DIRBE.defaults
are zodi/old/ defaults necessary to have in the repo on this push?

2024-03-27 09:22 UTC, hermda02 commented on commander3/parameter_files/defaults/components/zodi/old/K98.defaults
are zodi/old/ defaults necessary to have in the repo on this push?

2024-03-27 09:22 UTC, hermda02 commented on commander3/parameter_files/defaults/components/zodi/old/K98_xyz_offset.defaults
are zodi/old/ defaults necessary to have in the repo on this push?

2024-03-27 09:22 UTC, hermda02 commented on commander3/parameter_files/defaults/components/zodi/old/Planck18.defaults
are zodi/old/ defaults necessary to have in the repo on this push?

2024-03-27 09:22 UTC, hermda02 commented on commander3/parameter_files/defaults/components/zodi/old/hyper_parameters.defaults
are zodi/old/ defaults necessary to have in the repo on this push?

2024-03-27 09:22 UTC, hermda02 commented on commander3/parameter_files/defaults/components/zodi/old/sampling.defaults
are zodi/old/ defaults necessary to have in the repo on this push?

2024-03-27 09:22 UTC, hermda02 commented on commander3/python/commander_tools/tod_tools/commander_tod.py
A few print statements were left in this push - remove before merge

2024-03-27 09:22 UTC, hermda02 commented on commander3/src/comm_comp_mod.f90
Commented lines left in - remove before merge

2024-03-27 09:22 UTC, hermda02 commented on commander3/src/comm_zodi_samp_mod.f90
Remove commented out lines before merge

2024-03-27 09:22 UTC, hermda02 commented on commander3/src/comm_zodi_mod.f90
Remove commented out lines before merge

2024-04-09 08:43 UTC, hermda02 requested changes
Modularization looks great -- again, removing commented out testing lines helps remove clutter from `master` branch.

2024-04-09 08:43 UTC, hermda02 commented on commander3/src/comm_diffuse_comp_smod.f90
Lots of testing lines still in file - remove before merging into master

2024-04-09 08:43 UTC, hermda02 commented on commander3/src/comm_ptsrc_comp_mod.f90
Should these commented out testing lines be kept? If so, perhaps add a `verbosity` if statement.

2024-04-09 08:43 UTC, hermda02 commented on commander3/src/comm_signal_mod.f90
Should these commented out testing lines be kept? If so, perhaps add a `verbosity` if statement.

2024-05-07 14:02 UTC, unfunfunt commented on commander3/parameter_files/defaults/components/zodi/old/DIRBE.defaults
@MetinSa claims these are archival kelsall parameters that people might still want to use for reference, so we will keep them in

2024-05-07 14:10 UTC, unfunfunt commented on commander3/src/comm_comp_mod.f90
Seems to have been fixed

2024-05-07 14:16 UTC, unfunfunt commented on commander3/src/comm_zodi_mod.f90
Same with this, no one wants to make the call to delete it. I tried

2024-05-07 14:16 UTC, unfunfunt commented on commander3/src/comm_zodi_samp_mod.f90
We think this might still be useful to future generations, so it is being left for now unfortunately

2024-05-07 14:17 UTC, unfunfunt commented on commander3/python/commander_tools/tod_tools/commander_tod.py
now fixed

2024-05-07 14:21 UTC, unfunfunt commented on commander3/parameter_files/defaults/components/dust/dust_DIRBE_localsampler.defaults
This parameter appears to no longer exist

2024-05-07 14:23 UTC, unfunfunt commented on commander3/src/comm_diffuse_comp_smod.f90
Seems to have been fixed

2024-05-07 14:24 UTC, unfunfunt commented on commander3/src/comm_ptsrc_comp_mod.f90
Seems fixed now

2024-05-07 14:24 UTC, unfunfunt commented on commander3/src/comm_signal_mod.f90
Also seems fixed

2024-05-07 14:26 UTC, unfunfunt approved these changes
Daniels comments have been addressed now

2024-05-07 14:35 UTC, hermda02 commented on commander3/src/comm_cr_mod.f90
Still some commented out code and tests but oh well.

2024-05-07 14:37 UTC, hermda02 commented on commander3/src/comm_diffuse_comp_smod.f90
Testing lines made it through here too.

2024-05-07 14:39 UTC, hermda02 commented on commander3/src/comm_nonlin_smod.f90
Lots of testing lines made it in here, which seems to make sense.

2024-05-07 14:41 UTC, hermda02 approved these changes
Still some commented out testing lines, but let's not let perfect be the enemy of good. Approved.

2024-05-07 14:41 UTC, merged